name: bsc
services:
  database:
    container_name: bsc-db
    restart: unless-stopped
    image: postgres:18.3
    shm_size: 128mb # set shared memory limit when using docker compose (https://hub.docker.com/_/postgres)
    environment:
      POSTGRES_DB: ${DB_NAME:-bsc}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
    volumes:
      - bsc-db-volume:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  bsc-db-volume: