spring.application.name=bsc
#---
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bsc}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:admin}
#---
spring.profiles.active=dev